server:
  servlet:
    context-path: /rbacservice
  port: 8770
spring:
  profiles:
    active: core
  application:
    name: rbacservice
  jackson:
    parser:
      allow-single-quotes: true
  redis:
    database: 0
    port: 6379
    host: 192.168.132.150
    password:
    timeout: 5000ms


  main:
    allow-bean-definition-overriding: true

  #  org.springframework.web: TRACE
#    com:
#      bzz:
#        cloud:
#          rbac:
#            dao: TRACE
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace


security:
  oauth2:
    client:
      clientId: unity_client_1
      clientSecret: admin
      userAuthorizationUri: http://oauthservice/oauthservice/oauth/authorize
      grant-type: password
      scope: read,write
      access-token-uri: http://oauthservice/oauthservice/oauth/token
    resource:
      userInfoUri: http://oauthservice/oauthservice/oauth/user
    authorization:
      check-token-access: http://oauthservice/oauthservice/oauth/check_token

oauthservice:
  ribbon:
    listOfServers: 192.168.10.153:5010
    FLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0 for BZZ
  try-host: http://localhost:${server.port}
