server:
  port: 8760
spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
      - id: gatewayservice
        predicates:
          - Method=GET,POST
          - Path=/gatewayservice/**
        uri: lb://gatewayservice
#        filters:
#         - RewritePath=/gatewayservice/?(?<segment>.*), /gatewayservice\{segment}
          ##        - PrefixPath=/bzzgateway
      - id: oauthservice
        predicates:
          - Method=GET,POST
          - Path=/oauthservice/**
        uri: lb://oauthservice
        filters:
#          - RewritePath=/oauthservice/?(?<segment>.*), /oauthservice$\{segment}
      - id: rbacservice
        predicates:
          - Method=GET,POST
          - Path=/rbacservice/**
#        filters:
#          - RewritePath=/rbacservice/?(?<segment>.*), /rbacservice$\{segment}
        uri: lb://rbacservice
      - id: codegen
        predicates:
          - Method=GET,POST
          - Path=/codegen/**
#        filters:
#          - RewritePath=/codegen/?(?<segment>.*), /codegen\{segment}
        uri: lb://codegen

oauthservice:
  ribbon:
    listOfServers: 192.168.10.153:5010
    FLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
rbacservice:
  ribbon:
    listOfServers: 192.168.10.153:8770
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#        - PrefixPath=/api


logging:
  level:
    com:
      netflix:
        loadbalancer: DEBUG
    org:
      springframework:
        cloud:
          gateway: trace
          client:
            discovery: DEBUG
          netflix:
            ribbon: DEBUG


ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
