server:
  port: 8760
spring:
  application:
    name: bzz-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: bzz-gateway
        uri: lb://bzz-gateway
        predicates:
        - Path=/bzzgateway
        filters:
        - PrefixPath=/bzzgateway
      - id: bzzoauth
        uri: lb://bzzoauth
        predicates:
        - Path=/bzzoauth
#        filters:
#        - PrefixPath=/bzzoauth

      - id: bzz-rbac-server
        uri: lb://bzz-rbac-server
        predicates:
        - Path=/sys
#        filters:
#        - PrefixPath=/sys


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG




