server:
  port: 8760
  servlet:
    context-path: /api/bzz-gateway
spring:
  application:
    name: bzz-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: bzz-gateway
        uri: lb://bzz-gateway
        predicates:
        - Path=/api/bzzgateway/{segment}
#       filters:
          ##        - PrefixPath=/bzzgateway

      - id: bzzoauth
        uri: lb://bzzoauth
        predicates:
        - Path=/api/bzzoauth/{segment}
#        filters:
#        - PrefixPath=/bzzoauth

      - id: bzz-rbac-server
        uri: lb://bzz-rbac-server
        predicates:
        - Path=/api/rbac/{segment}
#        filters:
#        - PrefixPath=/api


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG




