server:
  port: 8760
  servlet:
    context-path: /gateway
spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: gatewayservice
        uri: lb://gatewayservice
        predicates:
        - Path=/gateway/**
#       filters:
          ##        - PrefixPath=/bzzgateway

      - id: oauthservice
        uri: lb://oauthservice
        predicates:
        - Path=/bzzoauth/**
#        filters:
#        - PrefixPath=/bzzoauth

      - id: rbacservice
        uri: lb://rbacservice
        predicates:
        - Path=/rbac/**
#        filters:
#        - PrefixPath=/api


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG




