server:
  port: 8760
spring:
  application:
    name: bzz-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: bzz-rbac-server
        uri: lb://bzz-rbac-server
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1




