server:
  port: 8760
spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: gatewayservice
        uri: lb://gatewayservice
        predicates:
        - Path=/gatewayservice/**
#       filters:
          ##        - PrefixPath=/bzzgateway
      - id: oauthservice
        uri: lb://oauthservice
        predicates:
        - Path=/oauthservice/**
#        filters:
#        - PrefixPath=/bzzoauth
      - id: rbacservice
        uri: lb://rbacservice
        predicates:
        - Path=/rbacservice/**

  oauthservice:
    ribbon:
      listOfServers: 192.168.1.3:5010
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  rbacservice:
    ribbon:
      listOfServers: 192.168.1.3:8770
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#        - PrefixPath=/api


logging:
  level:
    com:
      netflix:
        loadbalancer: DEBUG
    org:
      springframework:
        cloud:
          gateway: trace
          client:
            discovery: DEBUG
          netflix:
            ribbon: DEBUG


ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full